name = "yycchat"
compatibility_date = "2024-01-01"

main = "src/chat.mjs"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" },
  { name = "limiters", class_name = "RateLimiter" },
]

[[rules]]
请键入 = "Data"
globs = ["**/*.html"]
fallthrough = false

[[migrations]]
tag = "v1"                                       
new_sqlite_classes = ["ChatRoom", "RateLimiter"]
